### PR TITLE
Port to Thunderbird 78

### PR DESCRIPTION
**Pull request by beatkz**
Issue #49 fixed.

* Due to onbeforeSend function, this addon works only TB v78 or later.

### CODE REVIEW

**Review by Meatian — COMMENTED** [review]
It works with TB78.3.1 to TB83.0a1, though, but countdown feature doesn't work with TB78.2.2 and recipients are not listed with TB78.1.1.  I'm debating if these should be recognized as bugs and be fixed, or change its "strict_min_version" into "78.3.1" instead of "78.0".

**Comment by beatkz** [comment]
Since it was a quick preparation at the timing when TB68 was forced to apply to TB78, the operation was unconfirmed for the version before forced application.
 I'm in favor of a minimum version of 78.3.1 or higher in the manifest😅

コメントありがとうございます。
TB68からTB78に強制適用になったタイミングでの急ごしらえだったため、強制適用前のバージョンについては動作未確認でした。
私はマニフェストで最低バージョンを78.3.1以上とするのには賛成です😅

**Comment by ranman3g** [comment]
Hi Metian, 
Good to see this back but it isn't working for me.  
Tried it with TB 78.3.3 and now just released 78.4.0. 

Confirmation window flashes by and goes away.  Leaves the message unable to send or save.  Only option is to close the message window.

Error log message came up on the Error Console:
image

**Comment by Meatian** [comment]
Hi, ranman3g.  Thanks for the report.
BTW, the files on the error message (msgHdrView.js, AddrBookManager.jsm) are not Confirm-Address's files. Also, Confirm-Address doesn't access to address book, just scans header of the mail being sent.  Could you list the add-ons currently installed to your Thunderbird (incl. disabled add-ons)?

**Pull request merged**
